site_name: Cloud-Docs

plugins:
  - diagrams:
      file_extension: ".diagrams.py"
      max_workers: 5
  - search

nav:
  - Getting Started: index.md
  - Install: install.md
  - Full Example: example.md
  - Table: tables.md
  - tab: taps.md
  - kubectl: kubectl.md
  - Terraform Doc: terraform_doc.md
  - example.tf.md
  - graphivz.md
#theme:
#   name: 'material'
#   palette:
#     primary: indigo
     #scheme: default

theme:
  name: 'material'
  palette:
    - scheme: teal
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  #- mdx_inline_graphviz
  #- markdown_inline_graphviz
  #- markdown_inline_graphviz
  - mdx_inline_graphviz

repo_url: https://github.com/bigg01/mkdocs-example-diagram
edit_uri: edit/main/docs/
